### PR TITLE
Fix failing tests to work with Django (4.0) main dev branch

### LINKED ISSUE #184: Tox tests failing for `djmain` (Django 4.0) environment because of deprecated/removed items
The tox tests for the `djmain` (Django 4.0) environment are currently failing because of two issues:

### 1) Removal of 'django.utils.translation.ugettext_lazy()' in Django 4.0

From Django 3.0 `django.utils.translation.ugettext_lazy()` is deprecated in favor of the function that it's an alias for, `django.utils.translation.gettext_lazy()`.  Source: [Django 3.0 release notes](https://docs.djangoproject.com/en/3.2/releases/3.0/#id3)

In Django 4.0, `django.utils.translation.ugettext_lazy()` will be removed. Source: [Django Deprecation Timeline](https://docs.djangoproject.com/en/3.2/internals/deprecation/#deprecation-removed-in-4-0)

This is causing an error when running the tox tests for `djmain`, e.g.:
```bash
  ...
  File "/Users/xxx/django-defender/defender/config.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/Users/xxx/django-defender/.tox/py39-djmain/lib/python3.9/site-packages/django/utils/translation/__init__.py)
```

Since it's just an alias, we should be able to swap out the old function `ugettext_lazy()` with the new one `gettext_lazy()`.  

### 2) Removal of 'providing_args' argument for 'django.dispatch.Signal' in Django 4.0
From Django 3.1
> The purely documentational `providing_args` argument for `Signal` is deprecated. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
Source [Django 3.1 release notes](https://docs.djangoproject.com/en/3.1/releases/3.1/#id2)

In Django 4.0
> The `providing_args` argument for `django.dispatch.Signal` will be removed.
Source: [Django Deprecation Timeline](https://docs.djangoproject.com/en/3.2/internals/deprecation/#deprecation-removed-in-4-0)

This is causing an error when running the tox tests for `djmain`, e.g.:
```bash
  ...
  File "/Users/xxx/django-defender/defender/signals.py", line 3, in <module>
    username_block = Signal(providing_args=["username"])
TypeError: __init__() got an unexpected keyword argument 'providing_args'
```

Which can be fixed by replacing `Signal(providing_args=["..."])` with `Signal()`, with the option of leaving the `providing_args` as a comment if necessary.

### PR DESCRIPTION
**Pull request by JonathanWillitts**
Fixes #184 

Tox tests are currently failing for `djmain` (Django 4.0) environment because of deprecated/removed items (see issue #184 for full details).  

This PR fixes those issues, by:
- replacing `ugettext_lazy()` with `gettext_lazy()` (for which it is an alias)
- removing the no longer supported `providing_args` argument when defining Signals.  

The PR also fixes a minor typo in the 'tox.ini` file

Note, the commented out `providing_args` were left in for reference, but can be completely removed if required.

### CODE REVIEW

**Review by kencochrane — APPROVED** [review]
Lgtm thank you
